In [1]:
import pandas as pd
import polars as pl

pd.set_option("display.max_columns", None)

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('uber.csv')

colunas_id = ['Booking ID', 'Customer ID']
for col in colunas_id:
    df[col] = df[col].astype(str).str.replace('"', '')

df['Data_Hora'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')
df = df.drop(columns=['Date', 'Time'])

colunas_numericas = [
    'Avg VTAT', 'Avg CTAT', 'Booking Value', 
    'Ride Distance', 'Driver Ratings', 'Customer Rating'
]

for col in colunas_numericas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

display(df.head())

,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Data_Hora
0,CNR5884300,No Driver Found,CID1982111,eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-23 12:29:38
1,CNR1326809,Incomplete,CID4604802,Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI,2024-11-29 18:01:39
2,CNR8494506,Completed,CID9202816,Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card,2024-08-23 08:56:10
3,CNR8906825,Completed,CID2610914,Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI,2024-10-21 17:17:25
4,CNR1950162,Completed,CID9933542,Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI,2024-09-16 22:08:00

In [ ]:
status_geral = df['Booking Status'].value_counts(normalize=True) * 100
print(status_geral.round(2).astype(str) + "%")
print("\n")

print("TAXA DE 'Driver not Found' POR VEICULO")
df_sem_motorista = df[df['Booking Status'] == 'No Driver Found']
sem_motorista_por_veiculo = df_sem_motorista['Vehicle Type'].value_counts()
print(sem_motorista_por_veiculo)
print("\n")

df_sucesso = df[df['Booking Status'] == 'Completed']

print("MÉTRICAS DAS CORRIDAS COMPLETADAS")
resumo_financeiro = df_sucesso.groupby('Vehicle Type').agg(
    Faturamento_Total=('Booking Value', 'sum'),
    Ticket_Medio=('Booking Value', 'mean'),
    Distancia_Media_km=('Ride Distance', 'mean'),
    Tempo_Espera_Medio_Min=('Avg VTAT', 'mean')
).round(2)

display(resumo_financeiro)

Booking Status
Completed                62.0%
Cancelled by Driver      18.0%
No Driver Found           7.0%
Cancelled by Customer     7.0%
Incomplete                6.0%
Name: proportion, dtype: str


TAXA DE 'Driver not Found' POR VEÍCULO
Vehicle Type
Auto             2681
Go Mini          2015
Go Sedan         1960
Bike             1503
Premier Sedan    1280
eBike             746
Uber XL           315
Name: count, dtype: int64


MÉTRICAS DAS CORRIDAS COMPLETADAS

,Faturamento_Total,Ticket_Medio,Distancia_Media_km,Tempo_Espera_Medio_Min
Vehicle Type,,,,
Auto,11727615.0,506.48,25.99,8.49
Bike,7144913.0,509.11,26.00,8.57
Go Mini,9411418.0,507.38,25.99,8.52
Go Sedan,8538560.0,512.03,25.98,8.49
Premier Sedan,5733655.0,509.57,25.95,8.47
Uber XL,1406256.0,505.30,25.72,8.59
eBike,3298157.0,503.46,26.34,8.54